version: '3.8'

services:
  # Microservicio de Creaci贸n
  creation-service:
    build: ./microservicio-creacion
    ports:
      - "3001:3001"
    container_name: ms-creacion
    restart: unless-stopped
    networks:
      - app-network

  # Microservicio de Consulta
  query-service:
    build: ./microservicio-consulta
    ports:
      - "3002:3002"
    container_name: ms-consulta
    restart: unless-stopped
    networks:
      - app-network

  # Microservicio de Actualizaci贸n
  update-service:
    build: ./microservicio-actualizacion
    ports:
      - "3003:3003"
    container_name: ms-actualizacion
    restart: unless-stopped
    networks:
      - app-network

  # Microservicio de Eliminaci贸n
  delete-service:
    build: ./microservicio-eliminacion
    ports:
      - "3004:3004"
    container_name: ms-eliminacion
    restart: unless-stopped
    networks:
      - app-network

  # Servicio de Logs
  logs-service:
    build: ./servicio-logs
    ports:
      - "3005:3005"
    container_name: ms-logs
    restart: unless-stopped
    networks:
      - app-network
  
  # Servicio de Orquestaci贸n
  orchestration-service:
    build: ./microservicio-orquestacion
    ports:
      - "3006:3006"
    container_name: ms-orquestacion
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Red personalizada para que los servicios se comuniquen
networks:
  app-network:
    driver: bridge