version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: users_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network    

  # Microservicio de Creaci贸n
  creation-service:
    build: ./microservicio-creacion
    env_file:
      - .env
    ports:
      - "3001:3001"
    container_name: ms-creacion
    depends_on:
    - postgres
    restart: unless-stopped
    networks:
      - app-network

  # Microservicio de Consulta
  query-service:
    build: ./microservicio-consulta
    env_file:
      - .env
    ports:
      - "3002:3002"
    container_name: ms-consulta
    depends_on:
    - postgres
    restart: unless-stopped
    networks:
      - app-network

  # Microservicio de Actualizaci贸n
  update-service:
    build: ./microservicio-actualizacion
    env_file:
      - .env
    ports:
      - "3003:3003"
    container_name: ms-actualizacion
    restart: unless-stopped
    networks:
      - app-network

  # Microservicio de Eliminaci贸n
  delete-service:
    build: ./microservicio-eliminacion
    env_file:
      - .env
    ports:
      - "3004:3004"
    container_name: ms-eliminacion
    restart: unless-stopped
    networks:
      - app-network

  # Servicio de Logs
  logs-service:
    build: ./servicio-logs
    env_file:
      - .env
    ports:
      - "3005:3005"
    container_name: ms-logs
    restart: unless-stopped
    networks:
      - app-network
  
  # Servicio de Orquestaci贸n
  orchestration-service:
    build: ./microservicio-orquestacion
    ports:
      - "3006:3006"
    container_name: ms-orquestacion
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Red personalizada para que los servicios se comuniquen
networks:
  app-network:
    driver: bridge
    
volumes:
  postgres_data:    